//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootcampLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAssignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseAssignments()
        {
            this.StudentAssignments = new HashSet<StudentAssignments>();
        }
    
        public int CourseID { get; set; }
        public int AssignmentID { get; set; }
    
        public virtual Assignments Assignments { get; set; }
        public virtual Courses Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignments> StudentAssignments { get; set; }
    }
}
