//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootcampLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssignments
    {
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public int AssignmentID { get; set; }
        public bool Submitted { get; set; }
        public Nullable<int> OralMark { get; set; }
        public Nullable<int> TotalMark { get; set; }
    
        public virtual CourseAssignments CourseAssignments { get; set; }
        public virtual CourseStudents CourseStudents { get; set; }
    }
}
